variables:
  PUBLISHPASS: $(PUBLISHKEY)

trigger:
  - master

pool:
  vmImage: "ubuntu-latest"

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: "12.x"
    displayName: "Install Node.js"

  - task: DownloadSecureFile@1
    name: mySecureFile
    inputs:
      secureFile: ""
      retryCount: "2"

  - task: InstallSSHKey@0
    inputs:
      knownHostsEntry: ""
      sshPublicKey: ""
      sshPassphrase: "$(PUBLISHPASS)"
      sshKeySecureFile: ""

  - script: |
      git config --global --add url."git@github.com:".insteadOf "https://github.com/"
      git config --local user.email "mail@tmirwald.de"
      git config --local user.name "70mm1"
      npm install --no-audit --progress=false      
      npm run deploy
    displayName: "npm install and deploy"